language: node_js
sudo: false

install:
  - npm install -g qunit mocha tape ava

env:
  - FRAMEWORK=ava   CMD=ava tests/ava.js -t > ava.tap
  - FRAMEWORK=mocha CMD=mocha tests/chai.js tests/unit-js.js -R json > mocha.json
  - FRAMEWORK=qunit CMD=qunit tests/qunit-tests.js > qunit.tap
  - FRAMEWORK=tape  CMD=tape tests/tape.js > tape.tap
script:
  - $CMD

after_script:
  - if [ "$FRAMEWORK" != "ava" ]; then FRAMEWORK_OPT=--framework=$FRAMEWORK; fi
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py | python - FRAMEWORK_OPT