language: node_js
sudo: false
node_js:
  - "node"

env:
  - FRAMEWORK=ava   CMD="ava tests/ava.js -t"                          OUTFILE=ava.tap    INSTALL=ava                  ANNOTATE_LOG=false
  - FRAMEWORK=mocha CMD="mocha tests/chai.js tests/unit-js.js -R json" OUTFILE=mocha.json INSTALL="mocha chai unit.js" ANNOTATE_LOG=true
  - FRAMEWORK=qunit CMD="qunit tests/qunit-tests.js"                   OUTFILE=qunit.tap  INSTALL=qunit                ANNOTATE_LOG=false
  - FRAMEWORK=tape  CMD="tape tests/tape.js"                           OUTFILE=tape.tap   INSTALL=tape                 ANNOTATE_LOG=true

install:
  - npm install $INSTALL
  - set -o pipefail

script:
  - $CMD | tee $OUTFILE 2> build.log
  - cat build.log

after_failure:
  - if [ "$ANNOTATE_LOG" = true ]; then; curl -s https://raw.githubusercontent.com/report-ci/scripts/master/annotate.py | python - --tool node --input build.log; fi

after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py | python - --framework=$FRAMEWORK