language: node_js
sudo: false
node_js:
  - "node"

env:
  - FRAMEWORK=ava   CMD="ava tests/ava.js -t"                          OUTFILE=ava.tap    INSTALL=ava
  - FRAMEWORK=mocha CMD="mocha tests/chai.js tests/unit-js.js -R json" OUTFILE=mocha.json INSTALL="mocha chai unit.js"
  - FRAMEWORK=qunit CMD="qunit tests/qunit-tests.js"                   OUTFILE=qunit.tap  INSTALL=qunit
  - FRAMEWORK=tape  CMD="tape tests/tape.js"                           OUTFILE=tape.tap   INSTALL=tape

install:
  - npm install $INSTALL
  - set -o pipefail

script:
  - $CMD | tee $OUTFILE

after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py | python - --framework=$FRAMEWORK